name: Weekly Commit Tracker

on:
  schedule:
    - cron: '0 0 * * *'   # 매일 UTC 00:00 (한국시간 09:00)
    - cron: '0 12 * * *'  # 매일 UTC 12:00 (한국시간 21:00)
  workflow_dispatch:

jobs:
  track-commits:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check weekly commits
        id: check_commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          USERNAME="${{ github.repository_owner }}"
          NOW=$(TZ='Asia/Seoul' date '+%Y-%m-%d %H:%M:%S')
          CURRENT_WEEKDAY=$(TZ='Asia/Seoul' date '+%u')
          
          echo "Current time (KST): $NOW"
          echo "Checking commits for user: $USERNAME"
          
          EXCLUDED_REPOS="weekly-commit-challenge"
          
          if [ "$CURRENT_WEEKDAY" -eq 1 ]; then
            # 월요일: 지난주 월요일~일요일 (완료된 주)
            WEEK_START=$(TZ='Asia/Seoul' date -d '7 days ago' '+%Y-%m-%d')
            WEEK_END=$(TZ='Asia/Seoul' date -d '1 day ago' '+%Y-%m-%d')
            PERIOD_TYPE="지난주"
          else
            # 화~일요일: 이번주 월요일~오늘 (진행중인 주)
            DAYS_SINCE_MONDAY=$((CURRENT_WEEKDAY - 1))
            WEEK_START=$(TZ='Asia/Seoul' date -d "$DAYS_SINCE_MONDAY days ago" '+%Y-%m-%d')
            WEEK_END=$(TZ='Asia/Seoul' date '+%Y-%m-%d')
            PERIOD_TYPE="이번주"
          fi
          
          echo "Week start: $WEEK_START, Week end: $WEEK_END"
          
          # 한국 시간을 UTC로 변환 (KST - 9시간)
          SINCE_DATE_UTC=$(TZ='UTC' date -d "$WEEK_START 00:00:00 KST" -Iseconds)
          UNTIL_DATE_UTC=$(TZ='UTC' date -d "$WEEK_END 23:59:59 KST" -Iseconds)
          
          echo "KST Week start: $WEEK_START 00:00:00"
          echo "KST Week end: $WEEK_END 23:59:59"
          echo "UTC Since date: $SINCE_DATE_UTC"
          echo "UTC Until date: $UNTIL_DATE_UTC"
          
          # GraphQL 쿼리 생성 (유저 정보와 커밋 정보 함께 조회)
          echo '{"query":"query($username: String!, $from: DateTime!, $to: DateTime!) { user(login: $username) { avatarUrl contributionsCollection(from: $from, to: $to) { totalCommitContributions commitContributionsByRepository { repository { name owner { login } } contributions { totalCount } } } } }","variables":{"username":"'$USERNAME'","from":"'$SINCE_DATE_UTC'","to":"'$UNTIL_DATE_UTC'"}}' > /tmp/query.json
          
          # GraphQL API 호출
          GRAPHQL_RESPONSE=$(curl -s -X POST \
            -H "Authorization: bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d @/tmp/query.json \
            "https://api.github.com/graphql")
          
          echo "GraphQL Response: $GRAPHQL_RESPONSE"
          
          # 유저 아바타 URL 추출
          AVATAR_URL=$(echo "$GRAPHQL_RESPONSE" | jq -r '.data.user.avatarUrl // ""')
          
          # 커밋 수 계산
          COMMIT_COUNT=$(echo "$GRAPHQL_RESPONSE" | jq --arg excluded "$EXCLUDED_REPOS" '
            .data.user.contributionsCollection.commitContributionsByRepository
            | map(select(.repository.name as $repo_name | ($excluded | split(",") | index($repo_name) | not)))
            | map(.contributions.totalCount)
            | add // 0
          ')
          
          if [ -z "$COMMIT_COUNT" ] || [ "$COMMIT_COUNT" = "null" ]; then
            COMMIT_COUNT=0
          fi
          
          echo "Commit count: $COMMIT_COUNT"
          echo "Avatar URL: $AVATAR_URL"
          
          echo "commit_count=$COMMIT_COUNT" >> $GITHUB_OUTPUT
          echo "period_start=$WEEK_START" >> $GITHUB_OUTPUT
          echo "period_end=$WEEK_END" >> $GITHUB_OUTPUT
          echo "period_type=$PERIOD_TYPE" >> $GITHUB_OUTPUT
          echo "avatar_url=$AVATAR_URL" >> $GITHUB_OUTPUT
          
          if [ $COMMIT_COUNT -gt 0 ]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Calculate week number
        id: week_number
        run: |
          YEAR=$(TZ='Asia/Seoul' date '+%Y')
          WEEK_NUMBER=$(node -e "
            // 한국 시간 기준으로 주차 계산
            const now = new Date();
            const kstOffset = 9 * 60 * 60 * 1000; // 9시간을 밀리초로
            const kstNow = new Date(now.getTime() + kstOffset);
            
            const target = new Date(kstNow.valueOf());
            const dayNr = (target.getDay() + 6) % 7; // 월요일을 0으로
            target.setDate(target.getDate() - dayNr + 3); // 목요일로 이동
            const jan4 = new Date(target.getFullYear(), 0, 4); // 1월 4일
            const dayDiff = (target - jan4) / 86400000;
            console.log(Math.ceil(dayDiff / 7));
          ")
          
          echo "week_number=$WEEK_NUMBER" >> $GITHUB_OUTPUT
          echo "Year: $YEAR, Week: $WEEK_NUMBER (KST 기준)"

      - name: Check today commits (Monday only)
        id: check_today
        if: steps.check_commits.outputs.period_type == '지난주'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          USERNAME="${{ github.repository_owner }}"
          EXCLUDED_REPOS="weekly-commit-challenge"
          
          # 오늘(월요일) 데이터 수집
          TODAY=$(TZ='Asia/Seoul' date '+%Y-%m-%d')
          
          echo "Collecting today's commits: $TODAY"
          
          # 한국 시간을 UTC로 변환
          SINCE_DATE_UTC=$(TZ='UTC' date -d "$TODAY 00:00:00 KST" -Iseconds)
          UNTIL_DATE_UTC=$(TZ='UTC' date -d "$TODAY 23:59:59 KST" -Iseconds)
          
          # GraphQL 쿼리 생성
          echo '{\"query\":\"query($username: String!, $from: DateTime!, $to: DateTime!) { user(login: $username) { avatarUrl contributionsCollection(from: $from, to: $to) { totalCommitContributions commitContributionsByRepository { repository { name owner { login } } contributions { totalCount } } } } }\",\"variables\":{\"username\":\"'$USERNAME'\",\"from\":\"'$SINCE_DATE_UTC'\",\"to\":\"'$UNTIL_DATE_UTC'\"}}' > /tmp/today_query.json
          
          # GraphQL API 호출
          GRAPHQL_RESPONSE=$(curl -s -X POST \
            -H \"Authorization: bearer $GITHUB_TOKEN\" \
            -H \"Content-Type: application/json\" \
            -d @/tmp/today_query.json \
            \"https://api.github.com/graphql\")
          
          # 커밋 수 계산
          TODAY_COMMIT_COUNT=$(echo \"$GRAPHQL_RESPONSE\" | jq --arg excluded \"$EXCLUDED_REPOS\" '
            .data.user.contributionsCollection.commitContributionsByRepository
            | map(select(.repository.name as $repo_name | ($excluded | split(\",\") | index($repo_name) | not)))
            | map(.contributions.totalCount)
            | add // 0
          ')
          
          if [ -z \"$TODAY_COMMIT_COUNT\" ] || [ \"$TODAY_COMMIT_COUNT\" = \"null\" ]; then
            TODAY_COMMIT_COUNT=0
          fi
          
          echo "Today's commit count: $TODAY_COMMIT_COUNT"
          
          echo "today_commit_count=$TODAY_COMMIT_COUNT" >> $GITHUB_OUTPUT
          echo "today_date=$TODAY" >> $GITHUB_OUTPUT
          
          if [ $TODAY_COMMIT_COUNT -gt 0 ]; then
            echo "today_success=true" >> $GITHUB_OUTPUT
          else
            echo "today_success=false" >> $GITHUB_OUTPUT
          fi

      - name: Update record.md
        run: |
          COMMIT_COUNT="${{ steps.check_commits.outputs.commit_count }}"
          SUCCESS="${{ steps.check_commits.outputs.success }}"
          WEEK_NUM="${{ steps.week_number.outputs.week_number }}"
          PERIOD_START="${{ steps.check_commits.outputs.period_start }}"
          PERIOD_END="${{ steps.check_commits.outputs.period_end }}"
          PERIOD_TYPE="${{ steps.check_commits.outputs.period_type }}"
          YEAR=$(TZ='Asia/Seoul' date '+%Y')
          
          # 주차 기간 계산
          START_DATE=$(TZ='Asia/Seoul' date -d "$PERIOD_START" '+%Y-%m-%d')
          START_WEEKDAY=$(TZ='Asia/Seoul' date -d "$START_DATE" '+%u')
          DAYS_TO_SUBTRACT=$((START_WEEKDAY - 1))
          MONDAY=$(TZ='Asia/Seoul' date -d "$START_DATE - $DAYS_TO_SUBTRACT days" '+%m/%d')
          SUNDAY=$(TZ='Asia/Seoul' date -d "$START_DATE - $DAYS_TO_SUBTRACT days + 6 days" '+%m/%d')
          WEEK_PERIOD="$MONDAY ~ $SUNDAY"
          
          if [ "$SUCCESS" = "true" ]; then
            STATUS_EMOJI="✅ 성공"
          else
            STATUS_EMOJI="🔄 진행중 ($COMMIT_COUNT개)"
          fi
          
          # 아바타 URL 가져오기
          AVATAR_URL="${{ steps.check_commits.outputs.avatar_url }}"
          
          # 월요일인지 확인
          if [ "$PERIOD_TYPE" = "지난주" ]; then
            # 월요일: 지난주 + 오늘 두 개의 기록 생성
            
            # 1. 지난주 기록
            echo '{"period":"'$WEEK_PERIOD'","periodType":"지난주","dateRange":"'$PERIOD_START' ~ '$PERIOD_END'","year":'$YEAR',"weekNumber":'$WEEK_NUM',"commitCount":'$COMMIT_COUNT',"success":'$SUCCESS',"status":"'$STATUS_EMOJI'","lastUpdated":"'$(TZ='Asia/Seoul' date -Iseconds)'","username":"${{ github.repository_owner }}","avatarUrl":"'$AVATAR_URL'"}' > record_last_week.json
            
            # 2. 오늘(이번주) 기록 
            TODAY_COMMIT_COUNT="${{ steps.check_today.outputs.today_commit_count }}"
            TODAY_SUCCESS="${{ steps.check_today.outputs.today_success }}"
            TODAY_DATE="${{ steps.check_today.outputs.today_date }}"
            
            # 이번주 주차 계산
            THIS_WEEK_NUM=$((WEEK_NUM + 1))
            
            # 이번주 기간 계산 (월요일~일요일)
            THIS_MONDAY=$(TZ='Asia/Seoul' date '+%m/%d')
            THIS_SUNDAY=$(TZ='Asia/Seoul' date -d '+6 days' '+%m/%d')
            THIS_WEEK_PERIOD="$THIS_MONDAY ~ $THIS_SUNDAY"
            
            if [ "$TODAY_SUCCESS" = "true" ]; then
              TODAY_STATUS_EMOJI="✅ 성공"
            else
              TODAY_STATUS_EMOJI="🔄 진행중 ($TODAY_COMMIT_COUNT개)"
            fi
            
            # record.json에 전체 기록 포함
            {
              echo '{'
              echo '  "username": "${{ github.repository_owner }}",'
              echo '  "avatarUrl": "'$AVATAR_URL'",'
              echo '  "lastUpdated": "'$(TZ='Asia/Seoul' date -Iseconds)'",'
              echo '  "records": ['
              
              # 기존 기록들 추가
              if [ -f record.md.bak ]; then
                first_record=true
                while IFS= read -r line; do
                  if [[ "$line" == "|"*"|"*"|"*"|"* && "$line" != *"기간"* && "$line" != *"---"* ]]; then
                    if [ "$first_record" = false ]; then echo '    ,'; fi
                    parts=($(echo "$line" | tr '|' ' '))
                    period="${parts[1]// /}"
                    week="${parts[2]// /}"
                    commits="${parts[3]// /}"
                    status="${parts[4]// /}"
                    success="false"
                    if [[ "$status" == *"✅"* && "$status" != *"🔄"* ]]; then
                      success="true"
                    fi
                    echo '    {'
                    echo '      "period": "'$period'",'
                    echo '      "week": "'$week'",'
                    echo '      "commits": '$commits','
                    echo '      "success": '$success','
                    echo '      "status": "'$status'"'
                    echo -n '    }'
                    first_record=false
                  fi
                done < record.md.bak
                echo ','
              fi
              
              # 지난주 기록 추가
              echo '    {'
              echo '      "period": "'$WEEK_PERIOD'",'
              echo '      "week": "'${YEAR}년 ${WEEK_NUM}주차'",'
              echo '      "commits": '$COMMIT_COUNT','
              echo '      "success": '$SUCCESS','
              echo '      "status": "'$STATUS_EMOJI'"'
              echo '    },'
              
              # 이번주 기록 추가
              echo '    {'
              echo '      "period": "'$THIS_WEEK_PERIOD'",'
              echo '      "week": "'${YEAR}년 ${THIS_WEEK_NUM}주차'",'
              echo '      "commits": '$TODAY_COMMIT_COUNT','
              echo '      "success": '$TODAY_SUCCESS','
              echo '      "status": "'$TODAY_STATUS_EMOJI'"'
              echo '    }'
              echo '  ]'
              echo '}'
            } > record.json
            
            # 기존 record.md 백업
            if [ -f record.md ]; then
              cp record.md record.md.bak
            fi
            
            # record.md에 두 기록 모두 포함 (오름차순: 오래된 것이 위로)
            {
              echo "# ${{ github.repository_owner }} - Weekly Commit Challenge Record"
              echo ""
              echo "## 📊 기록 테이블"
              echo ""
              echo "| 기간 | 주차 | 커밋 수 | 성공 여부 |"
              echo "| --- | --- | --- | --- |"
            } > record.md
            
            # 기존 기록이 있다면 추가 (오름차순 유지)
            if [ -f record.md.bak ]; then
              # 기존 데이터 추출하여 추가
              grep "^|.*|.*|.*|.*|$" record.md.bak | grep -v "기간\|---" >> record.md || true
            fi
            
            # 새 기록들 추가 (지난주 먼저, 이번주 나중에)
            echo "| $WEEK_PERIOD | ${YEAR}년 ${WEEK_NUM}주차 | $COMMIT_COUNT | $STATUS_EMOJI |" >> record.md
            echo "| $THIS_WEEK_PERIOD | ${YEAR}년 ${THIS_WEEK_NUM}주차 | $TODAY_COMMIT_COUNT | $TODAY_STATUS_EMOJI |" >> record.md
            
          else
            # 화~일요일: 전체 기록 포함
            {
              echo '{'
              echo '  "username": "${{ github.repository_owner }}",'
              echo '  "avatarUrl": "'$AVATAR_URL'",'
              echo '  "lastUpdated": "'$(TZ='Asia/Seoul' date -Iseconds)'",'
              echo '  "records": ['
              
              # 기존 기록들 추가
              if [ -f record.md.bak ]; then
                first_record=true
                while IFS= read -r line; do
                  if [[ "$line" == "|"*"|"*"|"*"|"* && "$line" != *"기간"* && "$line" != *"---"* ]]; then
                    if [ "$first_record" = false ]; then echo '    ,'; fi
                    parts=($(echo "$line" | tr '|' ' '))
                    period="${parts[1]// /}"
                    week="${parts[2]// /}"
                    commits="${parts[3]// /}"
                    status="${parts[4]// /}"
                    success="false"
                    if [[ "$status" == *"✅"* && "$status" != *"🔄"* ]]; then
                      success="true"
                    fi
                    echo '    {'
                    echo '      "period": "'$period'",'
                    echo '      "week": "'$week'",'
                    echo '      "commits": '$commits','
                    echo '      "success": '$success','
                    echo '      "status": "'$status'"'
                    echo -n '    }'
                    first_record=false
                  fi
                done < record.md.bak
                echo ','
              fi
              
              # 현재 기록 추가
              echo '    {'
              echo '      "period": "'$WEEK_PERIOD'",'
              echo '      "week": "'${YEAR}년 ${WEEK_NUM}주차'",'
              echo '      "commits": '$COMMIT_COUNT','
              echo '      "success": '$SUCCESS','
              echo '      "status": "'$STATUS_EMOJI'"'
              echo '    }'
              echo '  ]'
              echo '}'
            } > record.json
            
            # 기존 record.md 백업
            if [ -f record.md ]; then
              cp record.md record.md.bak
            fi
            
            {
              echo "# ${{ github.repository_owner }} - Weekly Commit Challenge Record"
              echo ""
              echo "## 📊 기록 테이블"
              echo ""
              echo "| 기간 | 주차 | 커밋 수 | 성공 여부 |"
              echo "| --- | --- | --- | --- |"
            } > record.md
            
            # 기존 기록이 있다면 추가 (오름차순 유지)
            if [ -f record.md.bak ]; then
              # 기존 데이터 추출하여 추가
              grep "^|.*|.*|.*|.*|$" record.md.bak | grep -v "기간\|---" >> record.md || true
            fi
            
            # 새 기록 추가
            echo "| $WEEK_PERIOD | ${YEAR}년 ${WEEK_NUM}주차 | $COMMIT_COUNT | $STATUS_EMOJI |" >> record.md
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # 월요일인 경우 추가 파일도 포함
          if [ "${{ steps.check_commits.outputs.period_type }}" = "지난주" ]; then
            git add record.md record.json record_last_week.json
          else
            git add record.md record.json
          fi
          
          if ! git diff --staged --quiet; then
            CURRENT_TIME=$(TZ='Asia/Seoul' date '+%m/%d %H:%M')
            PERIOD_TYPE="${{ steps.check_commits.outputs.period_type }}"
            if [ "$PERIOD_TYPE" = "지난주" ]; then
              git commit -m "📊 ${{ steps.week_number.outputs.week_number }}주차 위클리 커밋 챌린지 기록 업데이트 (월요일: 지난주+이번주) ($CURRENT_TIME)"
            else
              git commit -m "📊 ${{ steps.week_number.outputs.week_number }}주차 위클리 커밋 챌린지 기록 업데이트 ($CURRENT_TIME)"
            fi
            git push
            echo "✅ 기록 파일 업데이트 완료"
          else
            echo "ℹ️ 변경사항이 없어 커밋하지 않습니다."
          fi
